#!/bin/zsh

# Download a file from one of my servers

# ARGUMENTS:
#    $1 str: absolute path to the target document or directory

# USAGE:
#   fetch path/to/file/on/server

fetch(){               
    local p=${PORTNM[${1[2,5]}]:-22}
    local s=${SERVER[${1[2,5]}]:-192.168.1.1}
    scp -o ConnectTimeout=3 -P$p $s:$1 ~/Documents/screpo
}

