#!/bin/zsh
spotstatus(){
	case $1 in
		start) $spotdir/spotstat.py > /dev/null & ;;
	    stop) kill $( ps | grep spotstat.py | grep -v grep | awk '{ print $1 }') > /dev/null ;;
		*) echo "USAGE: $(basename $0) [arguments: start stop]" && return 1 ;;
	esac
}
