#!/bin/zsh
spotstatus(){
	case $1 in
		start) /Users/kafka/Documents/devops/plib/projects/spotify-api/src/spotstat.py & ;;
	    stop) kill $( ps | grep spotstat.py | grep -v grep | awk '{ print $1 }') > /dev/null ;;
		*) echo "USAGE: $(basename $0) [arguments: start stop]" && return 1 ;;
	esac
}
