#!/bin/zsh
# activate/deactivate wifi device
# ARGUMENTS:
#   up: activate wifi
#   down: deactivate wifi
#   networks: list avaiable visible wifi networks

wifi(){
   test -z "$1" && echo "arguments: up down networks"; return 1   
   
   if isin up down $1; then
      ifconfig en0 $1

   elif isin networks $1; then
       airport -s
   
   else 
       echo "USAGE: $(basename $0)" 
       echo "[up: enable wifi interface] [down: disable wifi interface]" 
       echo "[networks: list available networks (wifi must be enabled)]"
       return 1
   fi
}
